version: '3.7'
services:
  web:
    image: odoo:13.0
    container_name: odoo13c
    networks:
      - default
      - pg_default
    external_links:
      - db:postgres
    ports:
      - "8139:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo      
      - ./etc:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
networks:
      default:
          driver: bridge
      pg_default:
          external: true      
volumes:
  odoo-web-data:        

