version: '3.7'
services:
  db:
    image: postgres:10
    container_name: db
    environment:
      - DB_PORT_5432_TCP_ADDR=postgres
      - DB_PORT_5432_TCP_PORT=5432
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - default
    ports:
      - "5435:5432" 
volumes:
  odoo-db-data:        

