version: '3.7'
services:
  web:
    image: odoo:14.0
    container_name: odoo14c
    command: -- -c /etc/odoo/odoo.conf -d odoo14c_sr-robot
    networks:
      - default
      - pg_default
    external_links:
      - db:odoo
    ports:
      - "8170:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo      
      - ./etc:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
networks:
      default:
          driver: bridge
      pg_default:
          external: true      
volumes:
    odoo-web-data:        

